version: '3.9'

services:
  dbpostgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
